### ISSUE TITLE
The sorting order of the output numeric part is out of order

### ISSUE THREAD

**Issue by insistxc** [doug-gilbert/sg3_utils#14]
Scanning SCSI subsystem for new devices
Scanning host 0 for  SCSI target IDs 0 1 2 3 4 5 6 7, all LUNs
 Scanning for device 0 0 0 0 ... 
OLD: Host: scsi0 Channel: 00 Id: 00 Lun: 00
      Vendor: VMware   Model: Virtual disk     Rev: 2.0 
      Type:   Direct-Access                    ANSI SCSI revision: 06
Scanning host 1 for  SCSI target IDs 0 1 2 3 4 5 6 7, all LUNs
Scanning host 10 for  SCSI target IDs 0 1 2 3 4 5 6 7, all LUNs
Scanning host 11 for  SCSI target IDs 0 1 2 3 4 5 6 7, all LUNs
Scanning host 12 for  SCSI target IDs 0 1 2 3 4 5 6 7, all LUNs
Scanning host 13 for  SCSI target IDs 0 1 2 3 4 5 6 7, all LUNs
Scanning host 14 for  SCSI target IDs 0 1 2 3 4 5 6 7, all LUNs
Scanning host 15 for  SCSI target IDs 0 1 2 3 4 5 6 7, all LUNs
Scanning host 16 for  SCSI target IDs 0 1 2 3 4 5 6 7, all LUNs
Scanning host 17 for  SCSI target IDs 0 1 2 3 4 5 6 7, all LUNs
Scanning host 18 for  SCSI target IDs 0 1 2 3 4 5 6 7, all LUNs
Scanning host 19 for  SCSI target IDs 0 1 2 3 4 5 6 7, all LUNs
Scanning host 2 for  SCSI target IDs 0 1 2 3 4 5 6 7, all LUNs
Scanning host 20 for  SCSI target IDs 0 1 2 3 4 5 6 7, all LUNs
Scanning host 21 for  SCSI target IDs 0 1 2 3 4 5 6 7, all LUNs
Scanning host 22 for  SCSI target IDs 0 1 2 3 4 5 6 7, all LUNs
Scanning host 23 for  SCSI target IDs 0 1 2 3 4 5 6 7, all LUNs
Scanning host 24 for  SCSI target IDs 0 1 2 3 4 5 6 7, all LUNs
Scanning host 25 for  SCSI target IDs 0 1 2 3 4 5 6 7, all LUNs
Scanning host 26 for  SCSI target IDs 0 1 2 3 4 5 6 7, all LUNs
Scanning host 27 for  SCSI target IDs 0 1 2 3 4 5 6 7, all LUNs
Scanning host 28 for  SCSI target IDs 0 1 2 3 4 5 6 7, all LUNs
Scanning host 29 for  SCSI target IDs 0 1 2 3 4 5 6 7, all LUNs
Scanning host 3 for  SCSI target IDs 0 1 2 3 4 5 6 7, all LUNs
Scanning host 30 for  SCSI target IDs 0 1 2 3 4 5 6 7, all LUNs
Scanning host 31 for  SCSI target IDs 0 1 2 3 4 5 6 7, all LUNs
Scanning host 32 for  SCSI target IDs 0 1 2 3 4 5 6 7, all LUNs
Scanning host 4 for  SCSI target IDs 0 1 2 3 4 5 6 7, all LUNs
Scanning host 6 for  SCSI target IDs 0 1 2 3 4 5 6 7, all LUNs
Scanning host 7 for  SCSI target IDs 0 1 2 3 4 5 6 7, all LUNs
Scanning host 8 for  SCSI target IDs 0 1 2 3 4 5 6 7, all LUNs
Scanning host 9 for  SCSI target IDs 0 1 2 3 4 5 6 7, all LUNs
0 new or changed device(s) found.          
0 remapped or resized device(s) found.
0 device(s) removed.               

v1.42 is normal

Scanning SCSI subsystem for new devices
Scanning host 0 for  SCSI target IDs  0 1 2 3 4 5 6 7, all LUNs
 Scanning for device 0 0 0 0 ... 
OLD: Host: scsi0 Channel: 00 Id: 00 Lun: 00
      Vendor: VMware   Model: Virtual disk     Rev: 2.0 
      Type:   Direct-Access                    ANSI SCSI revision: 06
Scanning host 1 for  SCSI target IDs  0 1 2 3 4 5 6 7, all LUNs
Scanning host 2 for  SCSI target IDs  0 1 2 3 4 5 6 7, all LUNs
Scanning host 3 for  SCSI target IDs  0 1 2 3 4 5 6 7, all LUNs
Scanning host 4 for  SCSI target IDs  0 1 2 3 4 5 6 7, all LUNs
 Scanning for device 4 0 0 0 ...           
OLD: Host: scsi4 Channel: 00 Id: 00 Lun: 00
      Vendor: NECVMWar Model: VMware SATA CD01 Rev: 1.00
      Type:   CD-ROM                           ANSI SCSI revision: 05
Scanning host 5 for  SCSI target IDs  0 1 2 3 4 5 6 7, all LUNs
Scanning host 6 for  SCSI target IDs  0 1 2 3 4 5 6 7, all LUNs
Scanning host 7 for  SCSI target IDs  0 1 2 3 4 5 6 7, all LUNs
Scanning host 8 for  SCSI target IDs  0 1 2 3 4 5 6 7, all LUNs
Scanning host 9 for  SCSI target IDs  0 1 2 3 4 5 6 7, all LUNs
Scanning host 10 for  SCSI target IDs  0 1 2 3 4 5 6 7, all LUNs
Scanning host 11 for  SCSI target IDs  0 1 2 3 4 5 6 7, all LUNs
Scanning host 12 for  SCSI target IDs  0 1 2 3 4 5 6 7, all LUNs
Scanning host 13 for  SCSI target IDs  0 1 2 3 4 5 6 7, all LUNs
Scanning host 14 for  SCSI target IDs  0 1 2 3 4 5 6 7, all LUNs
Scanning host 15 for  SCSI target IDs  0 1 2 3 4 5 6 7, all LUNs
Scanning host 16 for  SCSI target IDs  0 1 2 3 4 5 6 7, all LUNs
Scanning host 17 for  SCSI target IDs  0 1 2 3 4 5 6 7, all LUNs
Scanning host 18 for  SCSI target IDs  0 1 2 3 4 5 6 7, all LUNs
Scanning host 19 for  SCSI target IDs  0 1 2 3 4 5 6 7, all LUNs
Scanning host 20 for  SCSI target IDs  0 1 2 3 4 5 6 7, all LUNs
Scanning host 21 for  SCSI target IDs  0 1 2 3 4 5 6 7, all LUNs
Scanning host 22 for  SCSI target IDs  0 1 2 3 4 5 6 7, all LUNs
Scanning host 23 for  SCSI target IDs  0 1 2 3 4 5 6 7, all LUNs
Scanning host 24 for  SCSI target IDs  0 1 2 3 4 5 6 7, all LUNs
Scanning host 25 for  SCSI target IDs  0 1 2 3 4 5 6 7, all LUNs
Scanning host 26 for  SCSI target IDs  0 1 2 3 4 5 6 7, all LUNs
Scanning host 27 for  SCSI target IDs  0 1 2 3 4 5 6 7, all LUNs
Scanning host 28 for  SCSI target IDs  0 1 2 3 4 5 6 7, all LUNs
Scanning host 29 for  SCSI target IDs  0 1 2 3 4 5 6 7, all LUNs
Scanning host 30 for  SCSI target IDs  0 1 2 3 4 5 6 7, all LUNs
Scanning host 31 for  SCSI target IDs  0 1 2 3 4 5 6 7, all LUNs
Scanning host 32 for  SCSI target IDs  0 1 2 3 4 5 6 7, all LUNs
0 new or changed device(s) found.          
0 remapped or resized device(s) found.
0 device(s) removed.

**Comment by mwilck** [comment]
Please test the fix from #15.

**Comment by doug-gilbert** [comment]
Patch #15 applied upstream and mirrored here as subversion revision 939.
Tested with scsi_debug driver with 12 hosts and rescan_scsi_bus.sh showed the hosts in numeric order.

**Comment by mwilck** [comment]
I suppose this issue can be closed.
