### ISSUE TITLE
rescan_scsi_bus.sh: Why it's pointless to do a target scan on FC ?

### ISSUE THREAD

**Issue by wenchao-hao** [doug-gilbert/sg3_utils#20]
There is comment in rescan_scsi_bus.sh fo FC host which would make it unable to scan single LUN, but what is the reason?
Why do not do target scan on FC?

```
  if [ -e "/sys/class/fc_host/host$host" ] ; then
    # It's pointless to do a target scan on FC
    issue_lip=/sys/class/fc_host/host$host/issue_lip
    if [ -e "$issue_lip" ] && [ "$lipreset" -ge 0 ] ; then
      echo 1 > "$issue_lip" 2> /dev/null;
      udevadm_settle
      [ "$lipreset" -gt 0 ] && sleep "$lipreset"
    fi
    channelsearch=
    idsearch=
```

**Comment by doug-gilbert** [comment]
Even though the rescan_scsi_bus.sh script is in sg3_utils, it is sourced from folks at Suse who asked me to "carry" it in sg3_utils. I have no experience with FC so I can't answer your question but did forward it on to some people who might be able to answer. If so I'll send a follow-up reply.

**Comment by wenchao-hao** [comment]
> If so I'll send a follow-up reply.

Thanks a lot for your answer. 
I would do some test and check if it is OK to scan target on FC. It the result is ok, I might submit a PR.

**Comment by wenchao-hao** [comment]
@doug-gilbert I tested and found it's ok to scan FC device via channel and target ID. I submitted a PR which add an option to address it.
